import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  libraryOneSidebar: [{type: 'autogenerated', dirName: 'library-one'}],
  libraryTwoSidebar: [{type: 'autogenerated', dirName: 'library-two'}],
};

export default sidebars;
